# @leosingleton/commonlibs - Common Libraries for TypeScript and .NET Core
# Copyright (c) Leo C. Singleton IV <leo@leosingleton.com>
# See LICENSE in the project root for license information.

pr: none

trigger:
  branches:
    include:
    - '*'

jobs:
  - job: Build
    timeoutInMinutes: 12
    cancelTimeoutInMinutes: 2
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - template: azure-pipelines-steps.yml
