name: CI

on: push

jobs:
  js:
    name: Build JavaScript NPM Package
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Install Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: https://registry.npmjs.org
    
    - name: Install NPM Packages
      run: cd js && npm install

    - name: Lint
      run: cd js && npm run lint

    - name: Compile
      run: cd js && npm run build

    - name: Execute Jest unit tests for Node support
      run: cd js && npm run test:node

    - name: Execute Karma unit tests for browser support
      run: cd js && npm run test:browser

    - name: Publish Code Coverage
      uses: codecov/codecov-action@v1
      with:
        file: js/build/coverage/node/cobertura-coverage.xml

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: commonlibs-js-${{ github.run_number }}
        path: |
          js/**
          !**/node_modules/**

    - name: Publish NPM Package
      if: github.ref == 'refs/heads/master'
      run: cd js && npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  dotnet:
    name: Build .NET Core NuGet Package
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Compile
      run: |
        cd dotnet/
        dotnet restore
        dotnet build
        dotnet publish -c Release

    - name: Run Unit Tests
      run: |
        cd dotnet/
        dotnet test UnitTests/LeoSingleton.CommonLibs.UnitTests.csproj

    - name: Publish NuGet Package
      if: github.ref == 'refs/heads/master'
      run: cd dotnet/ && echo TODO
